# MkDocs configuration
site_name: "ezieView"

docs_dir: "docs"
site_url: "https://ezieview.github.io"
repo_url: https://bitbucket.org/aplkaiju/ezieview.git

theme:
  name: "material"
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.sections

plugins:
- search
- to-pdf:
    author: The JHUAPL EZIE Team
    copyright: Copyright @ JHUAPL 2026
    cover: false
    output_path: ezieView.pdf
    toc_level: 5
    enabled_if_env: ENABLE_PDF_EXPORT

- mkdocstrings:
    enabled: true
#   !ENV [ENABLE_MKDOCSTRINGS, true]
#   custom_templates: templates
    default_handler: python
    locale: en
    handlers:
      python:
        options:
          docstring_style: google
          show_source: false
          show_root_heading: true
          # !ENV [ENABLE_PDF_EXPORT, false]

nav:
  - Home: README.md
  - License: LICENSE.md
  - API Reference: api/index.md
  # - Getting Started: getting_started.md
  # - Tutorials: tutorials/index.md