[build-system]
requires = ["uv_build >= 0.9.0","uv_build < 0.13"]
build-backend = "uv_build"

[project]
name = "ezieView"
version = "0.1.5"
authors = [
  { name = "EZIE Support", email = "ezie-support@jhuapl.edu" },
]
description = "Plotting routines for the EZIE Level 1, 2, and 3 data products"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "apexpy",
  "cartopy",
  "click",
  "matplotlib",
  "netCDF4",
  "numpy",
  "requests",
  "scipy",
  "spiceypy",
]

[project.scripts]
view_coverage = "ezieview.update_coverage_plots:main" 
view_orbits = "ezieview.update_orbit_plots:main" 

[tool.setuptools.package-data]
"ezieview.binary-assets" = ["*.png"]

[tool.ruff]
lint.ignore=[
"N999",
"BLE001",
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
default = true

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Aurora",
  "Topic :: Scientific/Engineering :: Ionosphere",
]
license = ["BSD 3-Clause"]
license-files = ["LICENSE.md"]

[project.urls]
Source = "https://bitbucket.org/aplkaiju/ezieview/"
"Science Gateway" = "https://eziegw.jhuapl.edu"

# TODO: The following still TBD
# Homepage = ""
# Documentation = ""
# Changelog = ""
# "Bug Tracker" = ""
# Discussions = ""
